version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: completionist
      MYSQL_USER: completionist
      MYSQL_PASSWORD: password
    volumes:
      - completionist-db:/var/lib/mysql
    ports:
      - '3306:3306'
  fpm:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - db
    links:
      - db
  nginx:
    image: nginx:1.18
    volumes:
      - ./src/:/var/www/html
      - ./.docker/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    links:
      - fpm
    ports:
      - '80:80'
    networks:
      default:
        aliases:
          - completionist.test

volumes:
  completionist-db:
